
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: machineremediations.machineremediation.kubevirt.io
spec:
  group: machineremediation.kubevirt.io
  names:
    kind: MachineRemediation
    listKind: MachineRemediationList
    plural: machineremediations
    shortNames:
    - mr
    - mrs
    singular: machineremediation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MachineRemediation is the schema for the MachineRemediation API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of MachineRemediation
          properties:
            machineName:
              description: MachineName contains the name of machine that should be
                remediate
              type: string
            savedAnnotations:
              additionalProperties:
                type: string
              description: 'Annotations is an unstructured key value map stored with
                a resource that may be set by external tools to store and retrieve
                arbitrary metadata. They are not queryable and should be preserved
                when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
              type: object
            savedLabels:
              additionalProperties:
                type: string
              description: 'Map of string keys and values that can be used to organize
                and categorize (scope and select) objects. May match selectors of
                replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
              type: object
            type:
              description: Type contains the type of the remediation
              type: string
          type: object
        status:
          description: Most recently observed status of MachineRemediation resource
          properties:
            endTime:
              format: date-time
              type: string
            reason:
              type: string
            startTime:
              format: date-time
              type: string
            state:
              description: RemediationState contains state of the remediation
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
